apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sforbiddefaultserviceaccount
spec:
  crd:
    spec:
      names:
        kind: K8sForbidDefaultServiceAccount
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sforbiddefaultserviceaccount

        violation[{"msg": msg}] {
          sa := input.review.object.spec.template.spec.serviceAccountName
          sa == "default"
          msg := "不允許使用 default ServiceAccount，請明確指定 SA"
        }

        violation[{"msg": msg}] {
          not input.review.object.spec.template.spec.serviceAccountName
          msg := "ServiceAccountName 不能為空，請明確指定 SA"
        }
